Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 260
Metrics/BlockLength:
  Max: 50
Metrics/MethodLength:
  Max: 20
Style/GuardClause:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false